media:
  input: /media
  output: /media
content:
  - name: site
    label: Site settings
    path: hugo.toml
    type: file
    fields:
      - name: title
        label: Website title
        type: string