baseURL = ''
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
title = 'Social Inclusion - Digital Accessibilty'
theme = 'hugo-liftoff'

[menus]
[[menus.main]]
    identifier = "projects"
    name = "Étude"
    url = "/projects/"
    weight = 1
[[menus.main]]
    identifier = "modules"
    name = "Modules d'offre"
    url = "/modules/"
    weight = 1
[[menus.main]]
    identifier = "interviews"
    name = "Interviews"
    url = "/interviews/"
    weight = 1
[[menus.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 20
[[menus.main]]
    identifier = "publication"
    name = "Publications"
    url = "/publication/"
    weight = 10


[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    title = "Humanity & Inclusion"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "Humanity & Inclusion"
