baseURL = ''
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
removePathAccents = true
title = 'Social Inclusion - Digital Accessibilty'
theme = 'hugo-liftoff'

[menus]
[[menus.main]]
    # Top-level menu entry
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 1

[[menus.main]]
    identifier = "interviews"
    name = "Interviews"
    url = "/interviews/"
    weight = 1
[[menus.main]]
    identifier = "people"
    name = "People"
    url = "/people/"
    weight = 1
[[menus.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 1

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    title = "Humanity & Inclusion"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "Humanity & Inclusion"